local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("BloxFruits Trade Scam", "GrapeTheme")
local Tab = Window:NewTab("Freeze")
local Section = Tab:NewSection("BLOX FRUITS TRADE SCAM")
Section:NewLabel("Auto Accept")
label:UpdateLabel("Freeze Trade")

Section:NewButton("Auto Accept", "", function()
    print("Clicked")
end)

Section:NewLabel("Freeze Trade")
Section:NewButton("Freeze", "", function()
    print("Clicked")
end)
